# Generated by Django 5.2.4 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_timetable_options_remove_timetable_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(default='CSE-A', max_length=50),
            preserve_default=False,
        ),
    ]
