# Generated by Django 5.2.4 on 2026-05-05 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_assignment_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['subject']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'subject')},
        ),
    ]
