# Generated by Django 5.2.4 on 2026-05-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_assignment_options_remove_assignment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
