# Generated by Django 5.2.4 on 2026-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_exam_delete_examplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
