# Generated by Django 5.2.4 on 2026-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='class_name',
            field=models.CharField(choices=[('CSE-A', 'CSE-A'), ('CSE-B', 'CSE-B'), ('BCA', 'BCA'), ('MCA', 'MCA')], default='CSE-A', max_length=20),
            preserve_default=False,
        ),
    ]
