# Generated by Django 5.2.4 on 2026-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sender_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=20),
            preserve_default=False,
        ),
    ]
