# Generated by Django 5.2.4 on 2026-05-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_event_options_remove_event_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studytracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='StudyTracker',
        ),
    ]
