# Generated by Django 5.2.4 on 2026-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_library_user_remove_studytracker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_name',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='class_name',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSC', 'BSc'), ('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50),
        ),
    ]
