# Generated by Django 5.2.4 on 2026-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_assignment_semester_attendance_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='class_name',
            field=models.CharField(choices=[('CSE-A', 'CSE-A'), ('CSE-B', 'CSE-B'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='semester',
            field=models.CharField(choices=[('SEM1', 'Sem 1'), ('SEM2', 'Sem 2'), ('SEM3', 'Sem 3'), ('SEM4', 'Sem 4'), ('SEM5', 'Sem 5'), ('SEM6', 'Sem 6'), ('SEM7', 'Sem 7'), ('SEM8', 'Sem 8')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
    ]
