# Generated by Django 5.2.4 on 2026-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_assignment_course_assignment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], default='BCA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('SEM1', 'Sem 1'), ('SEM2', 'Sem 2'), ('SEM3', 'Sem 3'), ('SEM4', 'Sem 4'), ('SEM5', 'Sem 5'), ('SEM6', 'Sem 6'), ('SEM7', 'Sem 7'), ('SEM8', 'Sem 8')], default='SEM1', max_length=10),
            preserve_default=False,
        ),
    ]
