# Generated by Django 5.2.4 on 2026-05-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_attendance_options_attendance_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('institution', 'enrollment_no')},
        ),
    ]
