# Generated by Django 5.2.4 on 2026-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_institution_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
